### ISSUE TITLE
Desert loot table includes Savanna and Badlands but not Desert itself

### ISSUE THREAD

**Issue by Jake-Norton** [ADHDMC/LocalizedFishingTables#3]
Pretty much what it says. I noticed this while looking at the code, quickly tested it, and found that fishing in a Desert biome returns Misc. loot table drops.

**Comment by RhythmicSys** [comment]
![image](https://github.com/Simplexity-Development/localized_fishing_tables/assets/45906780/56d00c02-4d1b-44d1-aef0-3204d7a1dac1)
🤦🏻 whoops lol, sorry about that, lemme fix that

**Comment by RhythmicSys** [comment]
Fixed in version [2.0.1](https://modrinth.com/datapack/localizedfishingtables/version/2.0.1) - though if any similar issues pop up please let me know, I definitely could've overlooked something else, this is a really long file and my dyslexia hates me
